### ISSUE TITLE
week9 todo list

### ISSUE THREAD

**Issue by ammydan** [ammydan/Kart-Microgame-OL#1]
1. add a countdown when player go into the game scene.
2. design the game end UI which include: winner name, go back to the lobby, winner total time.
3. finish the game end logic, when player finish the game, the game end UI just pop up.
4. study and try to make a dedicated server in the cloud, so people can connect to the game from all over the world( plan to use the microsoft playfab.
5. all developers should write a record for self work and give it to reviewer.
6. Tuesday reviewers check the progress and should collect the information of developers about the process; checkers should update the EDD, technical paper and prepare the next week's PPT.

**Comment by ammydan** [comment]
@XinheY 

- [ ] design the game end UI which include: winner name, go back to the lobby, winner total time.

**Comment by ammydan** [comment]
@RookyKestral001 

- [ ] add a countdown when player go into the game scene.

**Comment by ammydan** [comment]
@ammydan 

- [ ] study and try to make a dedicated server in the cloud, so people can connect to the game from all over the world( plan to use the microsoft playfab.

**Comment by ammydan** [comment]
@yushanweng 

- [ ] all developers should write a record for self work and give it to reviewer.

- [ ] Tuesday reviewers check the progress and should collect the information of developers about the process; checkers should update the EDD, technical paper and prepare the next week's PPT.

**Comment by ammydan** [comment]
@lukeblackrock 

- [ ] finish the game end logic, when player finish the game, the game end UI just pop up.
